nome = input("Digite seu Nome: ")
Idade = input("Digite sua idade: ")
Sexo = input("Digite o Genero: ")
Endereco = input("Digite seu endereço: ")
Tel = input("Digite seu telefone ")
print("Nome: \n", nome)
print("Idade: \n", Idade)
print("Sexo: \n", Sexo)
print("Endereco: \n", Endereco)
print("Tel: \n", Tel)
